CREATE TABLE [dbo].[EDI_Transactions] (
    [TransID]                BIGINT         IDENTITY (1, 1) NOT NULL,
    [TransType]              NCHAR (3)      NOT NULL,
    [LogID]                  BIGINT         NOT NULL,
    [ProcessorApp]           NVARCHAR (10)  NOT NULL,
    [SourceApp]              NVARCHAR (10)  NOT NULL,
    [LineNumber]             NVARCHAR (10)  NOT NULL,
    [VendorID]               NVARCHAR (20)  NOT NULL,
    [OrderNumber]            NVARCHAR (20)  NOT NULL,
    [ResponseNumber]         NVARCHAR (20)  NULL,
    [ASNNumber]              NVARCHAR (13)  NULL,
    [InvoiceNumber]          NVARCHAR (10)  NULL,
    [IssueDateTime]          DATETIME       NOT NULL,
    [PurposeCode]            NVARCHAR (20)  NOT NULL,
    [CurrencyCode]           NVARCHAR (3)   NULL,
    [CountryCode]            NCHAR (2)      NULL,
    [FillTermsCode]          NVARCHAR (50)  NULL,
    [TotalPayable]           NVARCHAR (30)  NULL,
    [OrderStatus]            NVARCHAR (30)  NOT NULL,
    [BuyerIDType]            NCHAR (3)      NOT NULL,
    [BuyerID]                NVARCHAR (12)  NOT NULL,
    [SourceIDType]           NCHAR (3)      NULL,
    [SourceID]               NVARCHAR (12)  NULL,
    [SellerIDType]           NCHAR (3)      NOT NULL,
    [SellerID]               NVARCHAR (12)  NOT NULL,
    [ShipToName]             NVARCHAR (30)  NOT NULL,
    [ShipToAddress1]         NVARCHAR (30)  NOT NULL,
    [ShipToAddress2]         NVARCHAR (30)  NOT NULL,
    [ShipToCity]             NVARCHAR (23)  NOT NULL,
    [ShipToState]            NCHAR (2)      NOT NULL,
    [ShipToZip]              NVARCHAR (10)  NOT NULL,
    [ShipToCountryCode]      NCHAR (2)      NOT NULL,
    [BillToName]             NVARCHAR (30)  NOT NULL,
    [BillToAddress1]         NVARCHAR (30)  NOT NULL,
    [BillToAddress2]         NVARCHAR (30)  NOT NULL,
    [BillToCity]             NVARCHAR (23)  NOT NULL,
    [BillToState]            NCHAR (2)      NOT NULL,
    [BillToZip]              NVARCHAR (10)  NOT NULL,
    [BillToCountryCode]      NCHAR (2)      NOT NULL,
    [TransportIDType]        NCHAR (4)      NULL,
    [TransportID]            NCHAR (3)      NULL,
    [Message]                NVARCHAR (160) NULL,
    [ProductIDType]          NVARCHAR (10)  NOT NULL,
    [ProductID]              NVARCHAR (14)  NOT NULL,
    [ItemDescription]        NVARCHAR (100) NULL,
    [UnitPrice]              NVARCHAR (20)  NULL,
    [OrderQuantity]          NVARCHAR (10)  NOT NULL,
    [ConfirmQuantity]        NVARCHAR (10)  NULL,
    [BackOrderQuantity]      NVARCHAR (10)  NULL,
    [CancelQuantity]         NVARCHAR (10)  NULL,
    [ShippedQuantity]        NVARCHAR (10)  NULL,
    [InvoiceQuantity]        NVARCHAR (10)  NULL,
    [OrderLineStatus]        NVARCHAR (30)  NULL,
    [LineStatusDescription]  NVARCHAR (50)  NULL,
    [ShipDateStatus]         NVARCHAR (30)  NULL,
    [ShipNoticeDate]         NVARCHAR (8)   NULL,
    [CarrierNamdCodeType]    NVARCHAR (30)  NULL,
    [CarrierNameCode]        NVARCHAR (50)  NULL,
    [CustomerOrderReference] NVARCHAR (20)  NULL,
    [PackageNumber]          NVARCHAR (22)  NULL,
    [PackageMarkTypeCode]    NVARCHAR (50)  NULL,
    [PackageMarkValue]       NVARCHAR (50)  NULL,
    [ChargeTypeCode]         NVARCHAR (20)  NULL,
    [ChargeTypeDescription]  NVARCHAR (50)  NULL,
    [ChargeAmount]           NVARCHAR (20)  NULL,
    [InsertDateTime]         DATETIME       CONSTRAINT [DF_EDI_Transactions_InsertDateTime] DEFAULT (getdate()) NOT NULL,
    CONSTRAINT [PK_EDI_Transactions] PRIMARY KEY CLUSTERED ([TransID] ASC),
    CONSTRAINT [FK_EDI_Transactions_EDI_Process_Log] FOREIGN KEY ([LogID]) REFERENCES [dbo].[EDI_Process_Log] ([LogID])
);

