CREATE TABLE [importX12].[TagSLN] (
    [SLNId]                        BIGINT       IDENTITY (1, 1) NOT NULL,
    [EDIFileId]                    INT          NOT NULL,
    [LineNumber]                   INT          NOT NULL,
    [ControlNumberGroup]           VARCHAR (25) NULL,
    [ControlNumberTransaction]     VARCHAR (25) NULL,
    [AssignedIdentification]       VARCHAR (20) NULL,
    [RelationshipCode_01]          VARCHAR (1)  NULL,
    [Quantity]                     VARCHAR (15) NULL,
    [CompositeUnitOfMeasure]       VARCHAR (99) NULL,
    [UnitPrice]                    VARCHAR (2)  NULL,
    [RelationshipCode_02]          VARCHAR (1)  NULL,
    [ProductServiceIDQualifier_01] VARCHAR (2)  NULL,
    [ProductServiceID_01]          VARCHAR (48) NULL,
    [ProductServiceIDQualifier_02] VARCHAR (2)  NULL,
    [ProductServiceID_02]          VARCHAR (48) NULL,
    [ProductServiceIDQualifier_03] VARCHAR (2)  NULL,
    [ProductServiceID_03]          VARCHAR (48) NULL,
    [ProductServiceIDQu4lifier_04] VARCHAR (2)  NULL,
    [ProductServiceID_04]          VARCHAR (48) NULL,
    [ProductServiceIDQualifier_05] VARCHAR (2)  NULL,
    [ProductServiceID_05]          VARCHAR (48) NULL,
    [ProductServiceIDQualifier_06] VARCHAR (2)  NULL,
    [ProductServiceID_06]          VARCHAR (48) NULL,
    [ProductServiceIDQualifier_07] VARCHAR (2)  NULL,
    [ProductServiceID_07]          VARCHAR (48) NULL,
    [ProductServiceIDQualifier_08] VARCHAR (2)  NULL,
    [ProductServiceID_08]          VARCHAR (48) NULL,
    [ProductServiceIDQualifier_09] VARCHAR (2)  NULL,
    [ProductServiceID_09]          VARCHAR (48) NULL,
    CONSTRAINT [PK_importEDI_SLN] PRIMARY KEY CLUSTERED ([SLNId] ASC),
    CONSTRAINT [FK_importEDI_SLN~importEDIFiles] FOREIGN KEY ([EDIFileId]) REFERENCES [importX12].[EDIFiles] ([EDIFileId])
);

