	create VIEW dbo.[810_INV_DTL]
		AS
			SELECT	 [AckId]
					,CAST([PONumber] AS CHAR(6)) AS [PONumber]
					,[IssueDate]
					,CAST([VendorId] AS NVARCHAR(20)) AS [VendorID]
					,CAST([ReferenceNo] AS NVARCHAR(20)) AS [ReferenceNo] 
					,CAST([ShipToLoc] AS NVARCHAR(5)) AS [ShipToLoc]
					,CAST([ShipToSAN] AS NVARCHAR(12))  AS [ShipToSAN]
					,CAST([BillToLoc] AS NVARCHAR(5))  AS [BillToLoc]
					,CAST([BillToSAN] AS NVARCHAR(12)) AS [BillToSAN]
					,CAST([ShipFromLoc] AS NVARCHAR(5))  AS [ShipFromLoc]
					,CAST([ShipFromSAN] AS NVARCHAR(12))  AS [ShipFromSAN]
					,CAST([TotalLines] AS INT) AS [TotalLines]
					,CAST([TotalQuantity] AS INT) AS [TotalQty]
					,CAST([CurrencyCode] AS NVARCHAR(5)) AS [CurrencyCode]
					,[InsertDateTime]
					,[Processed]			
					,[ProcessedDateTime]
					,[ResponseACKSent]
					,CAST([ResponseAckNo] AS NVARCHAR(10)) AS [ResponseAckNo]
					,CAST([GSNo] AS NVARCHAR(10)) AS [GSNo]
			FROM EDI.AcknowledgeHeader