
CREATE VIEW [dbo].[810_INV_HDR]
			AS
			SELECT	 [InvoiceId] 
					,CAST([InvoiceNo] AS NVARCHAR(20)) AS [InvoiceNo]
					,CAST([IssueDate] AS DATETIME) AS [IssueDate]
					,CAST([VendorId] AS NVARCHAR(20)) [VendorID]
					,CAST([PONumber] AS NCHAR(6)) [PONumber]
					,CAST([ReferenceNo] AS NVARCHAR(20)) AS [ReferenceNo]
					,CAST([ShipToLoc] AS NVARCHAR(5)) AS [ShipToLoc]
					,CAST([ShipToSAN] AS NVARCHAR(12)) AS [ShipToSAN]
					,CAST([BillToLoc] AS NVARCHAR(5)) AS [BillToLoc]
					,CAST([BillToSAN] AS NVARCHAR(12)) AS [BillToSAN]
					,CAST([ShipFromLoc] AS NVARCHAR(5)) AS [ShipFromLoc]
					,CAST([ShipFromSAN] AS NVARCHAR(12)) AS [ShipFromSAN]
					,CAST([TotalLines] AS INT) AS [TotalLines]
					,[TotalQuantity] AS [TotalQty]
					,[TotalPayable] 
					,CAST([CurrencyCode] AS NVARCHAR(5)) AS [CurrencyCode]
					,[InsertDateTime]
					,[Processed]
					,[ProcessedDateTime]
					,[InvoiceACKSent]
					,CAST([InvoiceAckNo] AS NVARCHAR(10)) AS [InvoiceAckNo]
					,CAST([GSNo] AS NVARCHAR(10)) AS [GSNo]
			FROM BLK.InvoiceHeader
