
CREATE VIEW [dbo].[855_ACK_DTL]
	AS 
		SELECT	 [AckItemId] AS [ItemAckID]
				,[AckId]
				,CAST([LineNo] AS NVARCHAR(10)) AS [LineNo]
				,CAST([LineStatusCode] AS NVARCHAR(10)) AS [LineStatusCode]
				,CAST([ItemStatusCode] AS NVARCHAR(10)) AS [ItemStatusCode]
				,CAST([UnitOfMeasure] AS NVARCHAR(3)) AS [UOM]
				,CAST([QuantityOrdered] AS INT) AS [OrdQty]
				,CAST([QuantityShipped] AS INT) AS [ShipQty]
				,CAST([QuantityCancelled] AS INT) AS [CanceledQty]	
				,CAST([QuantityBackordered] AS INT) AS [BackOrdQty]
				,CAST([UnitPrice] AS NVARCHAR(10)) AS [UnitPrice]
				,CAST([PriceCode] AS NVARCHAR(10)) AS [PriceCode]
				,CAST([CurrencyCode] AS NVARCHAR(5)) AS [CurrencyCode]
				,CAST([ItemIdCode] AS NVARCHAR(5)) AS [ItemIdCode]
				,CAST([ItemIdentifier] AS NVARCHAR(20)) AS [ItemIdentifier]
				,CAST([ItemDesc] AS NVARCHAR(250)) AS [ItemDesc]
				,CAST([EDIFileID] AS INT) AS [EDIFileID]
				,CAST([EDILineNumber] AS INT) AS [EDILineNumber]
		FROM [BLK].[AcknowledgeDetail] 
