using System.Collections.Generic;
using DataHPBEDI.Models.MetaData.X12_3060;

namespace FormatX12_3060.Models.Abstracted
{
	public abstract class AK1
	{
		public AK1()
		{
			Meta_IdentifierCodes=new List<MetaCodes>
			{
				new MetaCodes("AB","Logistics Service Request (219)"),
				new MetaCodes("AA","Account Analysis (822)"),
				new MetaCodes("AD","Individual Life, Annuity and Disability Application (267)"),
				new MetaCodes("AF","Application for Admission to Educational Institutions (189)"),
				new MetaCodes("AG","Application Advice (824)"),
				new MetaCodes("AH","Logistics Service Response (220)"),
				new MetaCodes("AI","Automotive Inspection Detail (928)"),
				new MetaCodes("AK","Student Educational Record (Transcript) Acknowledgment (131)"),
				new MetaCodes("AL","Set Cancellation (998) and Application Acceptance/Rejection Advice (499)"),
				new MetaCodes("AN","Return Merchandise Authorization and Notification (180)"),
				new MetaCodes("AO","Income or Asset Offset (521)"),
				new MetaCodes("AR","Warehouse Stock Transfer Shipment Advice (943)"),
				new MetaCodes("AS","Transportation Appointment Schedule Information (163)"),
				new MetaCodes("AT","Animal Toxicological Data (249)"),
				new MetaCodes("AW","Warehouse Inventory Adjustment Advice (947)"),
				new MetaCodes("BC","Business Credit Report (155)"),
				new MetaCodes("BE","Benefit Enrollment and Maintenance (834)"),
				new MetaCodes("BF","Business Entity Filings (105)"),
				new MetaCodes("BL","Motor Carrier Bill of Lading (211)"),
				new MetaCodes("BS","Shipment and Billing Notice (857)"),
				new MetaCodes("CA","Purchase Order Change Acknowledgment/Request - Seller Initiated (865)"),
				new MetaCodes("CB","Unemployment Insurance Tax Claim or Charge Information (153)"),
				new MetaCodes("CC","Clauses and Provisions (504)"),
				new MetaCodes("CD","Credit/Debit Adjustment (812)"),
				new MetaCodes("CE","Cartage Work Assignment (222)"),
				new MetaCodes("CF","Corporate Financial Adjustment Information (844 and 849)"),
				new MetaCodes("CG","Administrative Message (994)"),
				new MetaCodes("CH","Car Handling Information (420)"),
				new MetaCodes("CI","Consolidated Service Invoice/Statement (811)"),
				new MetaCodes("CJ","Manufacturer Coupon Family Code Structure(877)"),
				new MetaCodes("CK","Manufacturer Coupon Redemption Detail (881)"),
				new MetaCodes("CM","Component Parts Content (871)"),
				new MetaCodes("CN","Coupon Notification (887)"),
				new MetaCodes("CO","Cooperative Advertising Agreements (290)"),
				new MetaCodes("CP","Electronic Proposal Information (251, 805)"),
				new MetaCodes("CR","Rail Car hire Settlements (414)"),
				new MetaCodes("CS","Cryptographic Service Message (815)"),
				new MetaCodes("CT","Application Control Totals (831)"),
				new MetaCodes("CV","Commercial Vehicle Safety and Credentials Information Exchange (285)"),
				new MetaCodes("D3","Contract Completion Status (567)"),
				new MetaCodes("D4","Contract Abstract (561)"),
				new MetaCodes("D5","Contract Payment Management Report (568)"),
				new MetaCodes("DA","Debit Authorization (828)"),
				new MetaCodes("DD","Shipment Delivery Discrepancy Information(854)"),
				new MetaCodes("DF","Market Development Fund Allocation (883)"),
				new MetaCodes("DI","Dealer Information (128)"),
				new MetaCodes("DM","Shipper's Car Order (422)"),
				new MetaCodes("DS","Data Status Tracking (242)"),
				new MetaCodes("DX","Direct Exchange Delivery and Return Information (894, 895)"),
				new MetaCodes("EC","Educational Course Inventory (188)"),
				new MetaCodes("ED","Student Educational Record (Transcript) (130)"),
				new MetaCodes("EI","Railroad Equipment Inquiry or Advice (456)"),
				new MetaCodes("ER","Revenue Receipts Statement (170)"),
				new MetaCodes("ES","Notice of Employment Status (540)"),
				new MetaCodes("EV","Railroad Event Report (451)"),
				new MetaCodes("EX","Excavation Communication (620)"),
				new MetaCodes("FA","Functional Acknowledgment (997)"),
				new MetaCodes("FB","Freight Invoice (859)"),
				new MetaCodes("FC","Court and Law Enforcement Information (175,176)"),
				new MetaCodes("FG","Motor Carrier Loading and Route Guide (217) "),
				new MetaCodes("FH","Motor Carrier Tariff Information (218)"),
				new MetaCodes("FR","Financial Reporting (821, 827)"),
				new MetaCodes("FT","File Transfer (996)"),
				new MetaCodes("GB","Average Agreement Demurrage (423)"),
				new MetaCodes("GC","Damage Claim Transaction Sets (920, 924,925, 926)"),
				new MetaCodes("GE","General Request, Response or Confirmation(814)"),
				new MetaCodes("GF","Response to a Load Tender (990)"),
				new MetaCodes("GL","Inter-modal Group Loading Plan (715)"),
				new MetaCodes("GP","Grocery Products Invoice (880)"),
				new MetaCodes("GR","Statistical Government Information (152)"),
				new MetaCodes("GT","Grant or Assistance Application (194)"),
				new MetaCodes("HB","Eligibility, Coverage or Benefit Information (271)"),
				new MetaCodes("HC","Health Care Claim (837)"),
				new MetaCodes("HI","Health Care Services Review Information(278)"),
				new MetaCodes("HN","Health Care Claim Status Notification (277)"),
				new MetaCodes("HP","Health Care Claim Payment/Advice (835)"),
				new MetaCodes("HR","Health Care Claim Status Request (276)"),
				new MetaCodes("HS","Eligibility, Coverage or Benefit Inquiry (270)"),
				new MetaCodes("IA","Air Freight Details and Invoice (110, 980)"),
				new MetaCodes("IB","Inventory Inquiry/Advice (846)"),
				new MetaCodes("IC","Rail Advance Interchange Consist (418)"),
				new MetaCodes("ID","Insurance/Annuity Application Status (273)"),
				new MetaCodes("IE","Insurance Producer Administration (252)"),
				new MetaCodes("IG","Direct Store Delivery Summary Information(882)"),
				new MetaCodes("II","Rail Freight Details and Invoice Summary(411)"),
				new MetaCodes("IJ","Report of Injury, Illness or Incident (148)"),
				new MetaCodes("IM","Motor Carrier Freight Details and Invoice (210,980)"),
				new MetaCodes("IN","Invoice Information (810,819)"),
				new MetaCodes("IO","Ocean Shipment Billing Details (310, 312, 980)"),
				new MetaCodes("IP","Inter-modal Ramp Activity (622)"),
				new MetaCodes("IR","Rail Carrier Freight Details and Invoice (410,980)"),
				new MetaCodes("IS","Estimated Time of Arrival and Car Scheduling(421) "),
				new MetaCodes("KM","Commercial Vehicle Credentials (286)"),
				new MetaCodes("LA","Federal Communications Commission (FCC) License Application (195)"),
				new MetaCodes("LB","Lock box (823)"),
				new MetaCodes("LI","Locomotive Information (436)"),
				new MetaCodes("LN","Property and Casualty Loss Notification (272)"),
				new MetaCodes("LR","Logistics Reassignment (536)"),
				new MetaCodes("LS","Asset Schedule (851)"),
				new MetaCodes("LT","Student Loan Transfer and Status Verification (144)"),
				new MetaCodes("MA","Motor Carrier Summary Freight Bill Manifest (224)"),
				new MetaCodes("MC","Request for Motor Carrier Rate Proposal (107)"),
				new MetaCodes("MD","Department of Defense Inventory Management (527)"),
				new MetaCodes("ME","Mortgage Origination (198, 200, 201, 261, 262, 263, 833, 872) "),
				new MetaCodes("MF","Market Development Funds Settlement (884)"),
				new MetaCodes("MG","Mortgage Servicing Transaction Sets (203,206, 260, 264, 266)"),
				new MetaCodes("MH","Motor Carrier Rate Proposal (106)"),
				new MetaCodes("MI","Motor Carrier Shipment Status Inquiry (213)"),
				new MetaCodes("MJ","Secondary Mortgage Market Loan Delivery (202)"),
				new MetaCodes("MK","Response to a Motor Carrier Rate Proposal (108)"),
				new MetaCodes("MM","Medical Event Reporting (500)"),
				new MetaCodes("MN","Mortgage Note (205)"),
				new MetaCodes("MO","Maintenance Service Order (650)"),
				new MetaCodes("MP","Motion Picture Booking Confirmation (159)"),
				new MetaCodes("MQ","Consolidators Freight Bill and Invoice (223)"),
				new MetaCodes("MR","Multilevel Rail car Load Details (125)"),
				new MetaCodes("MS","Material Safety Data Sheet (848)"),
				new MetaCodes("MT","Electronic Form Structure (868)"),
				new MetaCodes("MV","Material Obligation Validation (517)"),
				new MetaCodes("MW","Rail Waybill Response (427)"),
				new MetaCodes("MX","Material Claim (847)"),
				new MetaCodes("MY","Response to a Cartage Work Assignment (225)"),
				new MetaCodes("NC","Non-conformance Report (842)"),
				new MetaCodes("NL","Name and Address Lists (101)"),
				new MetaCodes("NP","Notice of Power of Attorney (157)"),
				new MetaCodes("NT","Notice of Tax Adjustment or Assessment (149)"),
				new MetaCodes("OC","Cargo Insurance Advice of Shipment (362)"),
				new MetaCodes("OG","Order Group - Grocery (875, 876)"),
				new MetaCodes("OR","Organizational Relationships (816)"),
				new MetaCodes("OW","Warehouse Shipping Order (940)"),
				new MetaCodes("PA","Price Authorization Acknowledgment/Status (845)"),
				new MetaCodes("PB","Railroad Parameter Trace Registration (455)"),
				new MetaCodes("PC","Purchase Order Change Request - Buyer Initiated (860) "),
				new MetaCodes("PD","Product Activity Data (852)"),
				new MetaCodes("PE","Periodic Compensation (256)"),
				new MetaCodes("PF","Annuity Activity (268)"),
				new MetaCodes("PG","Insurance Plan Description (100)"),
				new MetaCodes("PH","Pricing History (503)"),
				new MetaCodes("PI","Patient Information (275)"),
				new MetaCodes("PJ","Project Schedule Reporting (806)"),
				new MetaCodes("PK","Project Cost Reporting (839) and Contractor Cost Data Reporting (196)"),
				new MetaCodes("PL","Railroad Problem Log Inquiry or Advice (452)"),
				new MetaCodes("PN","Product Source Information (244)"),
				new MetaCodes("PO","Purchase Order (850)"),
				new MetaCodes("PQ","Property Damage Report (112)"),
				new MetaCodes("PR","Purchase Order Acknowledgment (855)"),
				new MetaCodes("PS","Planning Schedule with Release Capability (830)"),
				new MetaCodes("PT","Product Transfer and Resale Report (867)"),
				new MetaCodes("PU","Motor Carrier Shipment Pick-up Notification (216)"),
				new MetaCodes("PV","Purchase Order Shipment Management Document (250)"),
				new MetaCodes("PY","Payment Cancellation Request (829)"),
				new MetaCodes("QG","Product Information (878, 879, 888, 889, 893, 896)"),
				new MetaCodes("QM","Transportation Carrier Shipment Status Message (214)"),
				new MetaCodes("QO","Ocean Shipment Status Information (313, 315)"),
				new MetaCodes("RA","Payment Order/Remittance Advice (820)"),
				new MetaCodes("RB","Railroad Clearance (470)"),
				new MetaCodes("RC","Receiving Advice/Acceptance Certificate (861)"),
				new MetaCodes("RD","Royalty Regulatory Report (185)"),
				new MetaCodes("RE","Warehouse Stock Receipt Advice (944)"),
				new MetaCodes("RH","Railroad Reciprocal Switch File (433)"),
				new MetaCodes("RI","Routing and Carrier Instruction (853) "),
				new MetaCodes("RJ","Railroad Mark Register Update Activity (434)"),
				new MetaCodes("RK","Standard Transportation Commodity Code Master (435)"),
				new MetaCodes("RL","Rail Industrial Switch List (423)"),
				new MetaCodes("RM","Railroad Station Master File (431)"),
				new MetaCodes("RN","Requisition Transaction (511)"),
				new MetaCodes("RO","Ocean Booking Information (300, 301,303)"),
				new MetaCodes("RP","Commission Sales Report (818)"),
				new MetaCodes("RQ","Request for Quotation (840) and Procurement Notices (836)"),
				new MetaCodes("RR","Response to Request For Quotation (843)"),
				new MetaCodes("RS","Order Status Information (869, 870)"),
				new MetaCodes("RT","Report of Test Results (863)"),
				new MetaCodes("RU","Railroad Retirement Activity (429)"),
				new MetaCodes("RV","Railroad Junctions and Interchanges Activity (437)"),
				new MetaCodes("RW","Rail Revenue Waybill (426)"),
				new MetaCodes("RX","Rail Description (432)"),
				new MetaCodes("RY","Request for Student Educational Record (Transcript) (146)"),
				new MetaCodes("RZ","Response to Request for Student Educational Record (Transcript) (147)"),
				new MetaCodes("SA","Air Shipment Information (104)"),
				new MetaCodes("SB","Switch Rails (424)"),
				new MetaCodes("SC","Price/Sales Catalog (832)"),
				new MetaCodes("SD","Student Loan Pre-Claims and Claims (191)"),
				new MetaCodes("SE","Shipper's Export Declaration (601)"),
				new MetaCodes("SG","SG Receiving Advice - Grocery (885)"),
				new MetaCodes("SH","Ship Notice/Manifest (856)"),
				new MetaCodes("SI","Shipment Information (858)"),
				new MetaCodes("SJ","Transportation Automatic Equipment Identification (160)"),
				new MetaCodes("SL","Student Loan Application and Guarantee (135,139)"),
				new MetaCodes("SM","Motor Carrier Load Tender (204)"),
				new MetaCodes("SN","Rail Route File Maintenance (475)"),
				new MetaCodes("SO",""),
				new MetaCodes("SP","Specifications/Technical Information (841)"),
				new MetaCodes("SQ","Production Sequence (866)"),
				new MetaCodes("SR","Rail Carrier Shipment Information (404, 419)"),
				new MetaCodes("SS","Shipping Schedule (862)"),
				new MetaCodes("ST","Railroad Service Commitment Advice (453)"),
				new MetaCodes("SU","Account Assignment/Inquiry and Service/Status (248)"),
				new MetaCodes("SV","Student Enrollment Verification (190)"),
				new MetaCodes("SW","Warehouse Shipping Advice (945)"),
				new MetaCodes("TA","Electronic Filing of Tax Return Data Acknowledgment (151)"),
				new MetaCodes("TC","Court Submission (176)"),
				new MetaCodes("TD","Trading Partner Profile (838)"),
				new MetaCodes("TF","Electronic Filing of Tax Return Data (813)"),
				new MetaCodes("TI","Tax Information Exchange (826)"),
				new MetaCodes("TM","Motor Carrier Delivery Trailer Manifest (212)"),
				new MetaCodes("TN","Tax Rate Notification (150)"),
				new MetaCodes("TO","Real Estate Title Services (197, 199, 265)"),
				new MetaCodes("TP","Rail Rate Transactions (460, 463, 466, 468, 485, 486, 490, 492, 494)"),
				new MetaCodes("TR","Train Sheet (161)"),
				new MetaCodes("TS","Transportation Services Tender (602)"),
				new MetaCodes("TT","Testing Results Request and Report (138)"),
				new MetaCodes("TX","Text Message (864)"),
				new MetaCodes("UA","Retail Account Characteristics (885)"),
				new MetaCodes("UB","Customer Call Reporting (886)"),
				new MetaCodes("UC","Uniform Commercial Code Filing (154)"),
				new MetaCodes("UD","Deduction Research Report (891)"),
				new MetaCodes("UI","Underwriting Information Services (255)"),
				new MetaCodes("UP","Motor Carrier Pick-up Manifest (215)"),
				new MetaCodes("UW","Insurance Underwriting Requirements Reporting (186)"),
				new MetaCodes("VA","Vehicle Application Advice (126)"),
				new MetaCodes("VB","Vehicle Baying Order (127)"),
				new MetaCodes("VC","Vehicle Shipping Order (120)"),
				new MetaCodes("VD","Vehicle Damage (124)"),
				new MetaCodes("VE","Vessel Content Details (109)"),
				new MetaCodes("VH","Vehicle Carrier Rate Update (129)"),
				new MetaCodes("VI","Voter Registration Information (280)"),
				new MetaCodes("VS","Vehicle Service (121)"),
				new MetaCodes("WA","Product Service Transaction Sets (140, 141,142, 143)"),
				new MetaCodes("WB","Rail Carrier Waybill Interchange (417)"),
				new MetaCodes("WG","Vendor Performance Review (501)"),
				new MetaCodes("WI","Wage Determination (288)"),
				new MetaCodes("WL","Well Information (625)"),
				new MetaCodes("WR","Shipment Weights (440)"),
				new MetaCodes("WT","Rail Waybill Request (425) "),
			};
			Meta_Data=new List<MetaData>
			{
				new MetaData("AK101",   "479",  "M",    "ID",   2, 2,   MetaData.UsageName.Required, string.Empty,   "Functional Identifier Code" ,          "FunctionalIdentifierCode",             Meta_IdentifierCodes),
				new MetaData("AK102",   "28",   "M",    "N0",   1, 9,   MetaData.UsageName.Used,     string.Empty,   "Quantity",                             "GroupControlNumber",                   null),
			};
		}

		public virtual List<MetaCodes> Meta_IdentifierCodes { get; internal set; }

		public virtual List<MetaData> Meta_Data { get; internal set;}
		
		/// <summary>
		/// AK101 479 Functional Identifier Code M ID 2/2
		/// </summary>
		public virtual string FunctionalIdentifierCode { get; set; }

		/// <summary>
		/// AK102 28 Group Control Number M N0 1/9
		/// </summary>		public virtual string GroupControlNumber { get; set; }
		public virtual string GroupControlNumber { get; set; }
	}
}
