using System.Collections.Generic;
using DataHPBEDI.Models.MetaData.X12_3060;

namespace FormatX12_3060.Models.Abstracted
{
	public abstract class AK2
	{

		public AK2()
		{
			Meta_IdentifierCodes=new List<MetaCodes>
			{
				new MetaCodes("100","Insurance Plan Description"),
				new MetaCodes("101","Name and Address Lists"),
				new MetaCodes("104","Air Shipment Information"),
				new MetaCodes("105","Business Entity Filings"),
				new MetaCodes("106","Motor Carrier Rate Proposal"),
				new MetaCodes("107","Request for Motor Carrier Rate Proposal"),
				new MetaCodes("108","Response to a Motor Carrier Rate Proposal"),
				new MetaCodes("109","Vessel Content Details"),
				new MetaCodes("110","Air Freight Details and Invoice"),
				new MetaCodes("112","Property Damage Report"),
				new MetaCodes("120","Vehicle Shipping Order"),
				new MetaCodes("121","Vehicle Service"),
				new MetaCodes("124","Vehicle Damage"),
				new MetaCodes("125","Multilevel Rail car Load Details"),
				new MetaCodes("126","Vehicle Application Advice"),
				new MetaCodes("127","Vehicle Baying Order"),
				new MetaCodes("128","Dealer Information"),
				new MetaCodes("129","Vehicle Carrier Rate Update"),
				new MetaCodes("130","Student Educational Record(Transcript)"),
				new MetaCodes("131","Student Educational Record(Transcript) Acknowledgment"),
				new MetaCodes("135","Student Loan Application"),
				new MetaCodes("138","Testing Results Request and Report"),
				new MetaCodes("139","Student Loan Guarantee Result"),
				new MetaCodes("140","Product Registration"),
				new MetaCodes("141","Product Service Claim Response"),
				new MetaCodes("142","Product Service Claim"),
				new MetaCodes("143","Product Service Notification"),
				new MetaCodes("144","Student Loan Transfer and Status Verification"),
				new MetaCodes("146","Request for Student Educational Record (Transcript)"),
				new MetaCodes("147","Response to Request for Student Educational Record (Transcript)"),
				new MetaCodes("148","Report of Injury, Illness or Incident"),
				new MetaCodes("149","Notice of Tax Adjustment or Assessment"),
				new MetaCodes("150","Tax Rate Notification"),
				new MetaCodes("151","Electronic Filing of Tax Return Data Acknowledgment"),
				new MetaCodes("152","Statistical Government Information"),
				new MetaCodes("153","Unemployment Insurance Tax Claim or Charge Information"),
				new MetaCodes("154","Uniform Commercial Code Filing"),
				new MetaCodes("155","Business Credit Report"),
				new MetaCodes("157","Notice of Power of Attorney"),
				new MetaCodes("159","Motion Picture Booking Confirmation"),
				new MetaCodes("160","Transportation Automatic Equipment Identification"),
				new MetaCodes("161","Train Sheet"),
				new MetaCodes("163","Transportation Appointment Schedule Information"),
				new MetaCodes("170","Revenue Receipts Statement"),
				new MetaCodes("175","Court and Law Enforcement Notice"),
				new MetaCodes("176","Court Submission"),
				new MetaCodes("180","Return Merchandise Authorization and Notification"),
				new MetaCodes("185","Royalty Regulatory Report"),
				new MetaCodes("186","Insurance Underwriting Requirements Reporting"),
				new MetaCodes("188","Educational Course Inventory"),
				new MetaCodes("189","Application for Admission to Educational Institutions"),
				new MetaCodes("190","Student Enrollment Verification"),
				new MetaCodes("191","Student Loan Pre-Claims and Claims"),
				new MetaCodes("194","Grant or Assistance Application"),
				new MetaCodes("195","Federal Communications Commission (FCC) License Application"),
				new MetaCodes("196","Contractor Cost Data Reporting"),
				new MetaCodes("197","Real Estate Title Evidence"),
				new MetaCodes("198","Loan Verification Information"),
				new MetaCodes("199","Real Estate Settlement Information"),
				new MetaCodes("200","Mortgage Credit Report"),
				new MetaCodes("201","Residential Loan Application"),
				new MetaCodes("202","Secondary Mortgage Market Loan Delivery"),
				new MetaCodes("203","Secondary Mortgage Market Investor Report"),
				new MetaCodes("204","Motor Carrier Load Tender"),
				new MetaCodes("205","Mortgage Note"),
				new MetaCodes("206","Real Estate Inspection"),
				new MetaCodes("210","Motor Carrier Freight Details and Invoice"),
				new MetaCodes("211","Motor Carrier Bill of Lading"),
				new MetaCodes("212","Motor Carrier Delivery Trailer Manifest"),
				new MetaCodes("213","Motor Carrier Shipment Status Inquiry"),
				new MetaCodes("214","Transportation Carrier Shipment Status Message"),
				new MetaCodes("215","Motor Carrier Pick-up Manifest"),
				new MetaCodes("216","Motor Carrier Shipment Pick-up Notification"),
				new MetaCodes("217","Motor Carrier Loading and Route Guide"),
				new MetaCodes("218","Motor Carrier Tariff Information"),
				new MetaCodes("219","Logistics Service Request"),
				new MetaCodes("220","Logistics Service Response"),
				new MetaCodes("222","Cartage Work Assignment"),
				new MetaCodes("223","Consolidators Freight Bill and Invoice"),
				new MetaCodes("224","Motor Carrier Summary Freight Bill Manifest"),
				new MetaCodes("225","Response to a Cartage Work Assignment"),
				new MetaCodes("242","Data Status Tracking"),
				new MetaCodes("244","Product Source Information"),
				new MetaCodes("248","Account Assignment/Inquiry and Service/Status"),
				new MetaCodes("249","Animal Toxicological Data"),
				new MetaCodes("250","Purchase Order Shipment Management Document"),
				new MetaCodes("251","Pricing Support"),
				new MetaCodes("252","Insurance Producer Administration"),
				new MetaCodes("255","Underwriting Information Services"),
				new MetaCodes("256","Periodic Compensation"),
				new MetaCodes("260","Application for Mortgage Insurance Benefits"),
				new MetaCodes("261","Real Estate Information Request"),
				new MetaCodes("262","Real Estate Information Report"),
				new MetaCodes("263","Residential Mortgage Insurance Application Response"),
				new MetaCodes("264","Mortgage Loan Default Status"),
				new MetaCodes("265","Real Estate Title Insurance Services Order"),
				new MetaCodes("266","Mortgage or Property Record Change Notification"),
				new MetaCodes("267","Individual Life, Annuity and Disability Application"),
				new MetaCodes("268","Annuity Activity"),
				new MetaCodes("270","Eligibility, Coverage or Benefit Inquiry"),
				new MetaCodes("271","Eligibility, Coverage or Benefit Information"),
				new MetaCodes("272","Property and Casualty Loss Notification"),
				new MetaCodes("273","Insurance/Annuity Application Status"),
				new MetaCodes("275","Patient Information"),
				new MetaCodes("276","Health Care Claim Status Request"),
				new MetaCodes("277","Health Care Claim Status Notification"),
				new MetaCodes("278","Health Care Services Review Information"),
				new MetaCodes("280","Voter Registration Information"),
				new MetaCodes("285","Commercial Vehicle Safety and Credentials Information Exchange"),
				new MetaCodes("286","Commercial Vehicle Credentials"),
				new MetaCodes("288","Wage Determination"),
				new MetaCodes("290","Cooperative Advertising Agreements"),
				new MetaCodes("300","Reservation (Booking Request) (Ocean)"),
				new MetaCodes("301","Confirmation (Ocean)"),
				new MetaCodes("303","Booking Cancellation (Ocean)"),
				new MetaCodes("304","Shipping Instructions"),
				new MetaCodes("306","Dock Receipt"),
				new MetaCodes("309","U.S. Customs Manifest"),
				new MetaCodes("310","Freight Receipt and Invoice (Ocean)"),
				new MetaCodes("311","Canadian Customs Information"),
				new MetaCodes("312","Arrival Notice (Ocean)"),
				new MetaCodes("313","Shipment Status Inquiry (Ocean)"),
				new MetaCodes("315","Status Details (Ocean)"),
				new MetaCodes("317","Delivery/Pickup Order"),
				new MetaCodes("319","Terminal Information"),
				new MetaCodes("321","Demurrage Guarantee (Ocean)"),
				new MetaCodes("322","Terminal Operations and Inter-modal Ramp Activity"),
				new MetaCodes("323","Vessel Schedule and Itinerary (Ocean)"),
				new MetaCodes("324","Vessel Stow Plan (Ocean)"),
				new MetaCodes("325","Consolidation of Goods in Container"),
				new MetaCodes("326","Consignment Summary List"),
				new MetaCodes("350","U.S. Customs Status Information"),
				new MetaCodes("352","U.S. Customs Carrier General Order Status"),
				new MetaCodes("353","U.S. Customs Events Advisory Details"),
				new MetaCodes("354","U.S. Customs Automated Manifest Archive Status"),
				new MetaCodes("355","U.S. Customs Acceptance/Rejection"),
				new MetaCodes("356","U.S. Customs Permit to Transfer Request"),
				new MetaCodes("357","U.S. Customs In-Bond Information"),
				new MetaCodes("358","U.S. Customs Consist Information"),
				new MetaCodes("361","Carrier Interchange Agreement (Ocean)"),
				new MetaCodes("362","Cargo Insurance Advice of Shipment"),
				new MetaCodes("404","Rail Carrier Shipment Information"),
				new MetaCodes("410","Rail Carrier Freight Details and Invoice"),
				new MetaCodes("411","Freight Details and Invoice Summary (Rail)"),
				new MetaCodes("414","Rail Car hire Settlements"),
				new MetaCodes("417","Rail Carrier Waybill Interchange"),
				new MetaCodes("418","Rail Advance Interchange Consist"),
				new MetaCodes("419","Advance Car Disposition"),
				new MetaCodes("420","Car Handling Information"),
				new MetaCodes("421","Estimated Time of Arrival and Car Scheduling"),
				new MetaCodes("422","Shipper's Car Order"),
				new MetaCodes("423","Rail Industrial Switch List"),
				new MetaCodes("425","Rail Waybill Request"),
				new MetaCodes("426","Rail Revenue Waybill"),
				new MetaCodes("429","Railroad Retirement Activity"),
				new MetaCodes("431","Railroad Station Master File"),
				new MetaCodes("432","Rail Description"),
				new MetaCodes("433","Railroad Reciprocal Switch File"),
				new MetaCodes("434","Railroad Mark Register Update Activity"),
				new MetaCodes("435","Standard Transportation Commodity Code Master"),
				new MetaCodes("436","Locomotive Information"),
				new MetaCodes("437","Railroad Junctions and Interchanges Activity"),
				new MetaCodes("440","Shipment Weights"),
				new MetaCodes("451","Railroad Event Report"),
				new MetaCodes("452","Railroad Problem Log Inquiry or Advice"),
				new MetaCodes("453","Railroad Service Commitment Advice"),
				new MetaCodes("455","Railroad Parameter Trace Registration"),
				new MetaCodes("456","Railroad Equipment Inquiry or Advice"),
				new MetaCodes("460","Railroad Price Distribution Request or Response"),
				new MetaCodes("463","Rail Rate Reply"),
				new MetaCodes("466","Rate Request"),
				new MetaCodes("468","Rate Docket Journal Log"),
				new MetaCodes("470","Railroad Clearance"),
				new MetaCodes("475","Rail Route File Maintenance"),
				new MetaCodes("485","Rate making Action"),
				new MetaCodes("486","Rate Docket Expiration"),
				new MetaCodes("490","Rate Group Definition"),
				new MetaCodes("492","Miscellaneous Rates"),
				new MetaCodes("494","Scale Rate Table"),
				new MetaCodes("500","Medical Event Reporting"),
				new MetaCodes("501","Vendor Performance Review"),
				new MetaCodes("503","Pricing History"),
				new MetaCodes("504","Clauses and Provisions"),
				new MetaCodes("511","Requisition"),
				new MetaCodes("517","Material Obligation Validation"),
				new MetaCodes("521","Income or Asset Offset"),
				new MetaCodes("527","Material Due-In and Receipt"),
				new MetaCodes("536","Logistics Reassignment"),
				new MetaCodes("540","Notice of Employment Status"),
				new MetaCodes("561","Contract Abstract"),
				new MetaCodes("567","Contract Completion Status"),
				new MetaCodes("568","Contract Payment Management Report"),
				new MetaCodes("601","U.S. Customs Export Shipment Information"),
				new MetaCodes("602","Transportation Services Tender"),
				new MetaCodes("620","Excavation Communication"),
				new MetaCodes("622","Inter-modal Ramp Activity"),
				new MetaCodes("625","Well Information"),
				new MetaCodes("650","Maintenance Service Order"),
				new MetaCodes("715","Inter-modal Group Loading Plan"),
				new MetaCodes("805","Contract Pricing Proposal"),
				new MetaCodes("806","Project Schedule Reporting"),
				new MetaCodes("810","Invoice"),
				new MetaCodes("811","Consolidated Service Invoice/Statement"),
				new MetaCodes("812","Credit/Debit Adjustment"),
				new MetaCodes("813","Electronic Filing of Tax Return Data"),
				new MetaCodes("814","General Request, Response or Confirmation"),
				new MetaCodes("815","Cryptographic Service Message"),
				new MetaCodes("816","Organizational Relationships"),
				new MetaCodes("818","Commission Sales Report"),
				new MetaCodes("819","Operating Expense Statement"),
				new MetaCodes("820","Payment Order/Remittance Advice"),
				new MetaCodes("821","Financial Information Reporting"),
				new MetaCodes("822","Account Analysis"),
				new MetaCodes("823","Lock box"),
				new MetaCodes("824","Application Advice"),
				new MetaCodes("826","Tax Information Exchange"),
				new MetaCodes("827","Financial Return Notice"),
				new MetaCodes("828","Debit Authorization"),
				new MetaCodes("829","Payment Cancellation Request"),
				new MetaCodes("830","Planning Schedule with Release Capability"),
				new MetaCodes("831","Application Control Totals"),
				new MetaCodes("832","Price/Sales Catalog"),
				new MetaCodes("833","Mortgage Credit Report Order"),
				new MetaCodes("834","Benefit Enrollment and Maintenance"),
				new MetaCodes("835","Health Care Claim Payment/Advice"),
				new MetaCodes("836","Procurement Notices"),
				new MetaCodes("837","Health Care Claim"),
				new MetaCodes("838","Trading Partner Profile"),
				new MetaCodes("839","Project Cost Reporting"),
				new MetaCodes("840","Request for Quotation"),
				new MetaCodes("841","Specifications/Technical Information"),
				new MetaCodes("842","Non-conformance Report"),
				new MetaCodes("843","Response to Request for Quotation"),
				new MetaCodes("844","Product Transfer Account Adjustment"),
				new MetaCodes("845","Price Authorization Acknowledgment/Status"),
				new MetaCodes("846","Inventory Inquiry/Advice"),
				new MetaCodes("847","Material Claim"),
				new MetaCodes("848","Material Safety Data Sheet"),
				new MetaCodes("849","Response to Product Transfer Account Adjustment"),
				new MetaCodes("850","Purchase Order"),
				new MetaCodes("851","Asset Schedule"),
				new MetaCodes("852","Product Activity Data"),
				new MetaCodes("853","Routing and Carrier Instruction"),
				new MetaCodes("854","Shipment Delivery Discrepancy Information"),
				new MetaCodes("855","Purchase Order Acknowledgment"),
				new MetaCodes("856","Ship Notice/Manifest"),
				new MetaCodes("857","Shipment and Billing Notice"),
				new MetaCodes("858","Shipment Information"),
				new MetaCodes("859","Freight Invoice"),
				new MetaCodes("860","Purchase Order Change Request - Buyer Initiated"),
				new MetaCodes("861","Receiving Advice/Acceptance Certificate"),
				new MetaCodes("862","Shipping Schedule"),
				new MetaCodes("863","Report of Test Results"),
				new MetaCodes("864","Text Message"),
				new MetaCodes("865","Purchase Order Change Acknowledgment/Request - Seller Initiated"),
				new MetaCodes("866","Production Sequence"),
				new MetaCodes("867","Product Transfer and Resale Report"),
				new MetaCodes("868","Electronic Form Structure"),
				new MetaCodes("869","Order Status Inquiry"),
				new MetaCodes("870","Order Status Report"),
				new MetaCodes("871","Component Parts Content"),
				new MetaCodes("872","Residential Mortgage Insurance Application"),
				new MetaCodes("875","Grocery Products Purchase Order"),
				new MetaCodes("876","Grocery Products Purchase Order Change"),
				new MetaCodes("877","Manufacturer Coupon Family Code Structure"),
				new MetaCodes("878","Product Authorization/De-Authorization"),
				new MetaCodes("879","Price Information"),
				new MetaCodes("880","Grocery Products Invoice"),
				new MetaCodes("881","Manufacturer Coupon Redemption Detail"),
				new MetaCodes("882","Direct Store Delivery Summary Information"),
				new MetaCodes("883","Market Development Fund Allocation"),
				new MetaCodes("884","Market Development Fund Settlement"),
				new MetaCodes("885","Retail Account Characteristics"),
				new MetaCodes("886","Customer Call Reporting"),
				new MetaCodes("887","Coupon Notification"),
				new MetaCodes("888","Item Maintenance"),
				new MetaCodes("889","Promotion Announcement"),
				new MetaCodes("891","Deduction Research Report"),
				new MetaCodes("893","Item Information Request"),
				new MetaCodes("894","Delivery/Return Base Record"),
				new MetaCodes("895","Delivery/Return Acknowledgment or Adjustment"),
				new MetaCodes("896","Product Dimension Maintenance"),
				new MetaCodes("920","Loss or Damage Claim - General Commodities"),
				new MetaCodes("924","Loss or Damage Claim - Motor Vehicle"),
				new MetaCodes("925","Claim Tracer"),
				new MetaCodes("926","Claim Status Report and Tracer Reply"),
				new MetaCodes("928","Automotive Inspection Detail"),
				new MetaCodes("940","Warehouse Shipping Order"),
				new MetaCodes("943","Warehouse Stock Transfer Shipment Advice"),
				new MetaCodes("944","Warehouse Stock Transfer Receipt Advice"),
				new MetaCodes("945","Warehouse Shipping Advice"),
				new MetaCodes("947","Warehouse Inventory Adjustment Advice"),
				new MetaCodes("980","Functional Group Totals"),
				new MetaCodes("990","Response To a Load Tender"),
				new MetaCodes("994","Administrative Message"),
				new MetaCodes("996","File Transfer"),
				new MetaCodes("997","Functional Acknowledgment"),
				new MetaCodes("998","Set Cancellation"),
			};

			Meta_Data=new List<MetaData>
			{
				new MetaData("AK201",   "143",  "M",    "ID",   3, 3,   MetaData.UsageName.Required, string.Empty,   "Transaction Set Identifier Code", "TransactionSetIdentifierCode",  Meta_IdentifierCodes),
				new MetaData("AK202",   "329",  "M",    "AN",   4, 9,   MetaData.UsageName.Used,     string.Empty,   "Transaction Set Control Number",  "TransactionSetControlNumber",   null),
			};
		}

		public virtual List<MetaCodes> Meta_IdentifierCodes { get; internal set; }

		public virtual List<MetaData> Meta_Data { get; internal set; }

		/// <summary>
		/// AK201 143 Transaction Set Identifier Code M ID 3/3
		/// </summary>
		public virtual string TransactionSetIdentifierCode { get; set; }

		/// <summary>
		/// AK202 329 Transaction Set Control Number M AN 4/9
		/// </summary>
		public virtual string TransactionSetControlNumber { get; set; }

	}
}