CREATE TABLE [IngramContent].[PurchaseOrder_Details] (
    [Id]                                   INT            IDENTITY (1, 1) NOT NULL,
    [ClientId]                             INT            NULL,
    [SpecialHandling_SpecialHandlingCodes] VARCHAR (30)   NULL,
    [Options_ShipToAccount]                VARCHAR (7)    NULL,
    [Options_POType]                       SMALLINT       NULL,
    [Options_OrderType]                    SMALLINT       NULL,
    [Options_DCCode]                       SMALLINT       NULL,
    [Options_Greenlight]                   BIT            NULL,
    [Options_POAType]                      SMALLINT       NULL,
    [Options_ShipToPassword]               VARCHAR (8)    NULL,
    [Options_CarrierShiping]               VARCHAR (25)   NULL,
    [Options_SplitOrder]                   NUMERIC (7, 4) NULL,
    [Cost_SalesTaxPercent]                 NUMERIC (6, 3) NULL,
    [Cost_FreightTaxPercent]               NUMERIC (6, 3) NULL,
    [Cost_FreightAmount]                   NUMERIC (7, 2) NULL,
    [Consumer_Name]                        VARCHAR (35)   NULL,
    [Consumer_PhoneNumber]                 VARCHAR (25)   NULL,
    [Consumer_Address]                     VARCHAR (35)   NULL,
    [Consumer_City]                        VARCHAR (25)   NULL,
    [Consumer_State]                       VARCHAR (3)    NULL,
    [Consumer_PostalCode]                  VARCHAR (11)   NULL,
    [Consumer_Country]                     VARCHAR (3)    NULL,
    [Recipient_Name]                       VARCHAR (35)   NULL,
    [Recipient_Validation]                 SMALLINT       NULL,
    [Recipient_Phone]                      VARCHAR (22)   NULL,
    [Recipient_Address]                    VARCHAR (35)   NULL,
    [Recipient_City]                       VARCHAR (25)   NULL,
    [Recipient_State]                      VARCHAR (3)    NULL,
    [Recipient_PostCode]                   VARCHAR (11)   NULL,
    [Recipient_Country]                    VARCHAR (3)    NULL,
    [Drop_GiftWrapFeeAmount]               DECIMAL (6, 2) NULL,
    [Drop_SendConsumerEmail]               BIT            NULL,
    [Drop_OrderLevelGift]                  SMALLINT       NULL,
    [Drop_SupressPrice]                    SMALLINT       NULL,
    [Drop_OrderLevelGiftWrapCode]          SMALLINT       NULL,
    [Delivery_SpecialDeliveryInstructions] VARCHAR (100)  NULL,
    [Marketing_Message]                    VARCHAR (255)  NULL,
    [Gift_Message]                         VARCHAR (255)  NULL,
    [Item1_ReferenceNumber]                VARCHAR (10)   NULL,
    [Item1_Number]                         VARCHAR (20)   NULL,
    [Item1_LineLevelBackorder]             SMALLINT       NULL,
    [Item1_SpecialActionCode]              SMALLINT       NULL,
    [Item1_NumberType]                     SMALLINT       NULL,
    [Item2_ClientListPrice]                DECIMAL (7, 2) NULL,
    [Item2_BackOrderCancelDate]            DATE           NULL,
    [Item2_GiftWrapCode]                   SMALLINT       NULL,
    [Item2_OrderQuantity]                  SMALLINT       NULL,
    [Item3_GiftMessage]                    VARCHAR (255)  NULL,
    [Imprint1_IndexCode]                   SMALLINT       NULL,
    [Imprint1_Text]                        SMALLINT       NULL,
    [Imprint1_Font]                        SMALLINT       NULL,
    [Imprint1_Color]                       SMALLINT       NULL,
    [Imprint1_Position]                    SMALLINT       NULL,
    [Imprint2_IndexCode]                   SMALLINT       NULL,
    [Imprint2_Text]                        SMALLINT       NULL,
    [Imprint2_Font]                        SMALLINT       NULL,
    [Imprint2_Color]                       SMALLINT       NULL,
    [Imprint2_Position]                    SMALLINT       NULL,
    [Imprint3_IndexCode]                   SMALLINT       NULL,
    [Imprint3_Text]                        SMALLINT       NULL,
    [Imprint3_Font]                        SMALLINT       NULL,
    [Imprint3_Color]                       SMALLINT       NULL,
    [Imprint3_Position]                    SMALLINT       NULL,
    CONSTRAINT [PK_PurchaseOrder_Details] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_MetaData.Codes~IngramContent.PurchaseOrder_Details-Color1] FOREIGN KEY ([Imprint1_Color]) REFERENCES [MetaData].[Codes] ([Id]),
    CONSTRAINT [FK_MetaData.Codes~IngramContent.PurchaseOrder_Details-Color2] FOREIGN KEY ([Imprint2_Color]) REFERENCES [MetaData].[Codes] ([Id]),
    CONSTRAINT [FK_MetaData.Codes~IngramContent.PurchaseOrder_Details-Color3] FOREIGN KEY ([Imprint3_Color]) REFERENCES [MetaData].[Codes] ([Id]),
    CONSTRAINT [FK_MetaData.Codes~IngramContent.PurchaseOrder_Details-DCCode] FOREIGN KEY ([Options_DCCode]) REFERENCES [MetaData].[Codes] ([Id]),
    CONSTRAINT [FK_MetaData.Codes~IngramContent.PurchaseOrder_Details-Font1] FOREIGN KEY ([Imprint1_Font]) REFERENCES [MetaData].[Codes] ([Id]),
    CONSTRAINT [FK_MetaData.Codes~IngramContent.PurchaseOrder_Details-Font2] FOREIGN KEY ([Imprint2_Font]) REFERENCES [MetaData].[Codes] ([Id]),
    CONSTRAINT [FK_MetaData.Codes~IngramContent.PurchaseOrder_Details-Font3] FOREIGN KEY ([Imprint3_Font]) REFERENCES [MetaData].[Codes] ([Id]),
    CONSTRAINT [FK_MetaData.Codes~IngramContent.PurchaseOrder_Details-GiftWrapCode] FOREIGN KEY ([Item2_GiftWrapCode]) REFERENCES [MetaData].[Codes] ([Id]),
    CONSTRAINT [FK_MetaData.Codes~IngramContent.PurchaseOrder_Details-IndexCode1] FOREIGN KEY ([Imprint1_IndexCode]) REFERENCES [MetaData].[Codes] ([Id]),
    CONSTRAINT [FK_MetaData.Codes~IngramContent.PurchaseOrder_Details-IndexCode2] FOREIGN KEY ([Imprint2_IndexCode]) REFERENCES [MetaData].[Codes] ([Id]),
    CONSTRAINT [FK_MetaData.Codes~IngramContent.PurchaseOrder_Details-IndexCode3] FOREIGN KEY ([Imprint3_IndexCode]) REFERENCES [MetaData].[Codes] ([Id]),
    CONSTRAINT [FK_MetaData.Codes~IngramContent.PurchaseOrder_Details-LineLevelBackorder] FOREIGN KEY ([Item1_LineLevelBackorder]) REFERENCES [MetaData].[Codes] ([Id]),
    CONSTRAINT [FK_MetaData.Codes~IngramContent.PurchaseOrder_Details-NumberType] FOREIGN KEY ([Item1_NumberType]) REFERENCES [MetaData].[Codes] ([Id]),
    CONSTRAINT [FK_MetaData.Codes~IngramContent.PurchaseOrder_Details-OrderLevelGift] FOREIGN KEY ([Drop_OrderLevelGift]) REFERENCES [MetaData].[Codes] ([Id]),
    CONSTRAINT [FK_MetaData.Codes~IngramContent.PurchaseOrder_Details-OrderLevelGiftwrapCode] FOREIGN KEY ([Drop_OrderLevelGiftWrapCode]) REFERENCES [MetaData].[Codes] ([Id]),
    CONSTRAINT [FK_MetaData.Codes~IngramContent.PurchaseOrder_Details-OrderType] FOREIGN KEY ([Options_OrderType]) REFERENCES [MetaData].[Codes] ([Id]),
    CONSTRAINT [FK_MetaData.Codes~IngramContent.PurchaseOrder_Details-POAType] FOREIGN KEY ([Options_POAType]) REFERENCES [MetaData].[Codes] ([Id]),
    CONSTRAINT [FK_MetaData.Codes~IngramContent.PurchaseOrder_Details-Position1] FOREIGN KEY ([Imprint1_Position]) REFERENCES [MetaData].[Codes] ([Id]),
    CONSTRAINT [FK_MetaData.Codes~IngramContent.PurchaseOrder_Details-Position2] FOREIGN KEY ([Imprint2_Position]) REFERENCES [MetaData].[Codes] ([Id]),
    CONSTRAINT [FK_MetaData.Codes~IngramContent.PurchaseOrder_Details-Position3] FOREIGN KEY ([Imprint3_Position]) REFERENCES [MetaData].[Codes] ([Id]),
    CONSTRAINT [FK_MetaData.Codes~IngramContent.PurchaseOrder_Details-Recipient_Validation] FOREIGN KEY ([Recipient_Validation]) REFERENCES [MetaData].[Codes] ([Id]),
    CONSTRAINT [FK_MetaData.Codes~IngramContent.PurchaseOrder_Details-SpecialActionCode] FOREIGN KEY ([Item1_SpecialActionCode]) REFERENCES [MetaData].[Codes] ([Id]),
    CONSTRAINT [FK_MetaData.Codes~IngramContent.PurchaseOrder_Details-SupressPrice] FOREIGN KEY ([Drop_SupressPrice]) REFERENCES [MetaData].[Codes] ([Id]),
    CONSTRAINT [FK_MetaData.Codes~IngramContent.PurchaseOrder_Details-Text1] FOREIGN KEY ([Imprint1_Text]) REFERENCES [MetaData].[Codes] ([Id]),
    CONSTRAINT [FK_MetaData.Codes~IngramContent.PurchaseOrder_Details-Text2] FOREIGN KEY ([Imprint2_Text]) REFERENCES [MetaData].[Codes] ([Id]),
    CONSTRAINT [FK_MetaData.Codes~IngramContent.PurchaseOrder_Details-Text3] FOREIGN KEY ([Imprint3_Text]) REFERENCES [MetaData].[Codes] ([Id]),
    CONSTRAINT [FK_NetaData.Codes~IngramContent.PurchaseOrder_Details-POType] FOREIGN KEY ([Options_POType]) REFERENCES [MetaData].[Codes] ([Id]),
    CONSTRAINT [FK_PurchaesOrder_Client~PurchaseOrder_Details] FOREIGN KEY ([ClientId]) REFERENCES [IngramContent].[PurchaseOrder_Client] ([Id])
);

